// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: position.proto
#ifndef GRPC_position_2eproto__INCLUDED
#define GRPC_position_2eproto__INCLUDED

#include "position.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace position {

class PositionService final {
 public:
  static constexpr char const* service_full_name() {
    return "position.PositionService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    std::unique_ptr< ::grpc::ClientReaderInterface< ::position::PositionResponse>> StreamPosition(::grpc::ClientContext* context, const ::position::PositionRequest& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::position::PositionResponse>>(StreamPositionRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::position::PositionResponse>> AsyncStreamPosition(::grpc::ClientContext* context, const ::position::PositionRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::position::PositionResponse>>(AsyncStreamPositionRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::position::PositionResponse>> PrepareAsyncStreamPosition(::grpc::ClientContext* context, const ::position::PositionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::position::PositionResponse>>(PrepareAsyncStreamPositionRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void StreamPosition(::grpc::ClientContext* context, const ::position::PositionRequest* request, ::grpc::ClientReadReactor< ::position::PositionResponse>* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientReaderInterface< ::position::PositionResponse>* StreamPositionRaw(::grpc::ClientContext* context, const ::position::PositionRequest& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::position::PositionResponse>* AsyncStreamPositionRaw(::grpc::ClientContext* context, const ::position::PositionRequest& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::position::PositionResponse>* PrepareAsyncStreamPositionRaw(::grpc::ClientContext* context, const ::position::PositionRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    std::unique_ptr< ::grpc::ClientReader< ::position::PositionResponse>> StreamPosition(::grpc::ClientContext* context, const ::position::PositionRequest& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::position::PositionResponse>>(StreamPositionRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::position::PositionResponse>> AsyncStreamPosition(::grpc::ClientContext* context, const ::position::PositionRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::position::PositionResponse>>(AsyncStreamPositionRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::position::PositionResponse>> PrepareAsyncStreamPosition(::grpc::ClientContext* context, const ::position::PositionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::position::PositionResponse>>(PrepareAsyncStreamPositionRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void StreamPosition(::grpc::ClientContext* context, const ::position::PositionRequest* request, ::grpc::ClientReadReactor< ::position::PositionResponse>* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientReader< ::position::PositionResponse>* StreamPositionRaw(::grpc::ClientContext* context, const ::position::PositionRequest& request) override;
    ::grpc::ClientAsyncReader< ::position::PositionResponse>* AsyncStreamPositionRaw(::grpc::ClientContext* context, const ::position::PositionRequest& request, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReader< ::position::PositionResponse>* PrepareAsyncStreamPositionRaw(::grpc::ClientContext* context, const ::position::PositionRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_StreamPosition_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status StreamPosition(::grpc::ServerContext* context, const ::position::PositionRequest* request, ::grpc::ServerWriter< ::position::PositionResponse>* writer);
  };
  template <class BaseClass>
  class WithAsyncMethod_StreamPosition : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_StreamPosition() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_StreamPosition() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamPosition(::grpc::ServerContext* /*context*/, const ::position::PositionRequest* /*request*/, ::grpc::ServerWriter< ::position::PositionResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStreamPosition(::grpc::ServerContext* context, ::position::PositionRequest* request, ::grpc::ServerAsyncWriter< ::position::PositionResponse>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(0, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_StreamPosition<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_StreamPosition : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_StreamPosition() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackServerStreamingHandler< ::position::PositionRequest, ::position::PositionResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::position::PositionRequest* request) { return this->StreamPosition(context, request); }));
    }
    ~WithCallbackMethod_StreamPosition() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamPosition(::grpc::ServerContext* /*context*/, const ::position::PositionRequest* /*request*/, ::grpc::ServerWriter< ::position::PositionResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::position::PositionResponse>* StreamPosition(
      ::grpc::CallbackServerContext* /*context*/, const ::position::PositionRequest* /*request*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_StreamPosition<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_StreamPosition : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_StreamPosition() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_StreamPosition() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamPosition(::grpc::ServerContext* /*context*/, const ::position::PositionRequest* /*request*/, ::grpc::ServerWriter< ::position::PositionResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_StreamPosition : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_StreamPosition() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_StreamPosition() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamPosition(::grpc::ServerContext* /*context*/, const ::position::PositionRequest* /*request*/, ::grpc::ServerWriter< ::position::PositionResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStreamPosition(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncWriter< ::grpc::ByteBuffer>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(0, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_StreamPosition : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_StreamPosition() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackServerStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const::grpc::ByteBuffer* request) { return this->StreamPosition(context, request); }));
    }
    ~WithRawCallbackMethod_StreamPosition() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamPosition(::grpc::ServerContext* /*context*/, const ::position::PositionRequest* /*request*/, ::grpc::ServerWriter< ::position::PositionResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::grpc::ByteBuffer>* StreamPosition(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/)  { return nullptr; }
  };
  typedef Service StreamedUnaryService;
  template <class BaseClass>
  class WithSplitStreamingMethod_StreamPosition : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithSplitStreamingMethod_StreamPosition() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::SplitServerStreamingHandler<
          ::position::PositionRequest, ::position::PositionResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerSplitStreamer<
                     ::position::PositionRequest, ::position::PositionResponse>* streamer) {
                       return this->StreamedStreamPosition(context,
                         streamer);
                  }));
    }
    ~WithSplitStreamingMethod_StreamPosition() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status StreamPosition(::grpc::ServerContext* /*context*/, const ::position::PositionRequest* /*request*/, ::grpc::ServerWriter< ::position::PositionResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with split streamed
    virtual ::grpc::Status StreamedStreamPosition(::grpc::ServerContext* context, ::grpc::ServerSplitStreamer< ::position::PositionRequest,::position::PositionResponse>* server_split_streamer) = 0;
  };
  typedef WithSplitStreamingMethod_StreamPosition<Service > SplitStreamedService;
  typedef WithSplitStreamingMethod_StreamPosition<Service > StreamedService;
};

}  // namespace position


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_position_2eproto__INCLUDED
