// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: state_message.proto
#ifndef GRPC_state_5fmessage_2eproto__INCLUDED
#define GRPC_state_5fmessage_2eproto__INCLUDED

#include "state_message.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace state_message {

class ShareStateService final {
 public:
  static constexpr char const* service_full_name() {
    return "state_message.ShareStateService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::state_message::AgentMessage, ::state_message::MapMessage>> ShareState(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::state_message::AgentMessage, ::state_message::MapMessage>>(ShareStateRaw(context));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::state_message::AgentMessage, ::state_message::MapMessage>> AsyncShareState(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::state_message::AgentMessage, ::state_message::MapMessage>>(AsyncShareStateRaw(context, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::state_message::AgentMessage, ::state_message::MapMessage>> PrepareAsyncShareState(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::state_message::AgentMessage, ::state_message::MapMessage>>(PrepareAsyncShareStateRaw(context, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void ShareState(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::state_message::AgentMessage,::state_message::MapMessage>* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientReaderWriterInterface< ::state_message::AgentMessage, ::state_message::MapMessage>* ShareStateRaw(::grpc::ClientContext* context) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::state_message::AgentMessage, ::state_message::MapMessage>* AsyncShareStateRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::state_message::AgentMessage, ::state_message::MapMessage>* PrepareAsyncShareStateRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    std::unique_ptr< ::grpc::ClientReaderWriter< ::state_message::AgentMessage, ::state_message::MapMessage>> ShareState(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriter< ::state_message::AgentMessage, ::state_message::MapMessage>>(ShareStateRaw(context));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::state_message::AgentMessage, ::state_message::MapMessage>> AsyncShareState(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::state_message::AgentMessage, ::state_message::MapMessage>>(AsyncShareStateRaw(context, cq, tag));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::state_message::AgentMessage, ::state_message::MapMessage>> PrepareAsyncShareState(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::state_message::AgentMessage, ::state_message::MapMessage>>(PrepareAsyncShareStateRaw(context, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void ShareState(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::state_message::AgentMessage,::state_message::MapMessage>* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientReaderWriter< ::state_message::AgentMessage, ::state_message::MapMessage>* ShareStateRaw(::grpc::ClientContext* context) override;
    ::grpc::ClientAsyncReaderWriter< ::state_message::AgentMessage, ::state_message::MapMessage>* AsyncShareStateRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReaderWriter< ::state_message::AgentMessage, ::state_message::MapMessage>* PrepareAsyncShareStateRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_ShareState_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status ShareState(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::state_message::MapMessage, ::state_message::AgentMessage>* stream);
  };
  template <class BaseClass>
  class WithAsyncMethod_ShareState : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ShareState() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_ShareState() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ShareState(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::state_message::MapMessage, ::state_message::AgentMessage>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestShareState(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::state_message::MapMessage, ::state_message::AgentMessage>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(0, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_ShareState<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_ShareState : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ShareState() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackBidiHandler< ::state_message::AgentMessage, ::state_message::MapMessage>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->ShareState(context); }));
    }
    ~WithCallbackMethod_ShareState() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ShareState(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::state_message::MapMessage, ::state_message::AgentMessage>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::state_message::AgentMessage, ::state_message::MapMessage>* ShareState(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  typedef WithCallbackMethod_ShareState<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_ShareState : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ShareState() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_ShareState() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ShareState(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::state_message::MapMessage, ::state_message::AgentMessage>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_ShareState : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ShareState() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_ShareState() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ShareState(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::state_message::MapMessage, ::state_message::AgentMessage>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestShareState(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(0, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ShareState : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ShareState() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackBidiHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->ShareState(context); }));
    }
    ~WithRawCallbackMethod_ShareState() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ShareState(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::state_message::MapMessage, ::state_message::AgentMessage>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* ShareState(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  typedef Service StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef Service StreamedService;
};

}  // namespace state_message


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_state_5fmessage_2eproto__INCLUDED
