// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: state_message.proto
// Protobuf C++ Version: 5.29.3

#include "state_message.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace state_message {

inline constexpr Position::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : row_{0},
        col_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Position::Position(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct PositionDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PositionDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PositionDefaultTypeInternal() {}
  union {
    Position _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PositionDefaultTypeInternal _Position_default_instance_;

inline constexpr AgentUpdate::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : agent_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        type_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR AgentUpdate::AgentUpdate(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct AgentUpdateDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AgentUpdateDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~AgentUpdateDefaultTypeInternal() {}
  union {
    AgentUpdate _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AgentUpdateDefaultTypeInternal _AgentUpdate_default_instance_;

inline constexpr CellState::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        value_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        position_{nullptr} {}

template <typename>
PROTOBUF_CONSTEXPR CellState::CellState(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct CellStateDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CellStateDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CellStateDefaultTypeInternal() {}
  union {
    CellState _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CellStateDefaultTypeInternal _CellState_default_instance_;

inline constexpr AgentState::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        agent_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        position_{nullptr} {}

template <typename>
PROTOBUF_CONSTEXPR AgentState::AgentState(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct AgentStateDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AgentStateDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~AgentStateDefaultTypeInternal() {}
  union {
    AgentState _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AgentStateDefaultTypeInternal _AgentState_default_instance_;

inline constexpr MapState::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : parcel_{},
        _cached_size_{0},
        _oneof_case_{} {}

template <typename>
PROTOBUF_CONSTEXPR MapState::MapState(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct MapStateDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MapStateDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~MapStateDefaultTypeInternal() {}
  union {
    MapState _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MapStateDefaultTypeInternal _MapState_default_instance_;

inline constexpr AgentMessage::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        agents_{},
        timestamp_{nullptr} {}

template <typename>
PROTOBUF_CONSTEXPR AgentMessage::AgentMessage(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct AgentMessageDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AgentMessageDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~AgentMessageDefaultTypeInternal() {}
  union {
    AgentMessage _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AgentMessageDefaultTypeInternal _AgentMessage_default_instance_;

inline constexpr MapMessage::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        map_states_{},
        timestamp_{nullptr} {}

template <typename>
PROTOBUF_CONSTEXPR MapMessage::MapMessage(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct MapMessageDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MapMessageDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~MapMessageDefaultTypeInternal() {}
  union {
    MapMessage _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MapMessageDefaultTypeInternal _MapMessage_default_instance_;
}  // namespace state_message
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_state_5fmessage_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_state_5fmessage_2eproto = nullptr;
const ::uint32_t
    TableStruct_state_5fmessage_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::state_message::Position, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::state_message::Position, _impl_.row_),
        PROTOBUF_FIELD_OFFSET(::state_message::Position, _impl_.col_),
        PROTOBUF_FIELD_OFFSET(::state_message::AgentState, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::state_message::AgentState, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::state_message::AgentState, _impl_.agent_id_),
        PROTOBUF_FIELD_OFFSET(::state_message::AgentState, _impl_.position_),
        ~0u,
        0,
        PROTOBUF_FIELD_OFFSET(::state_message::AgentMessage, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::state_message::AgentMessage, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::state_message::AgentMessage, _impl_.timestamp_),
        PROTOBUF_FIELD_OFFSET(::state_message::AgentMessage, _impl_.agents_),
        0,
        ~0u,
        PROTOBUF_FIELD_OFFSET(::state_message::CellState, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::state_message::CellState, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::state_message::CellState, _impl_.position_),
        PROTOBUF_FIELD_OFFSET(::state_message::CellState, _impl_.value_),
        0,
        ~0u,
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::state_message::AgentUpdate, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::state_message::AgentUpdate, _impl_.agent_id_),
        PROTOBUF_FIELD_OFFSET(::state_message::AgentUpdate, _impl_.type_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::state_message::MapState, _internal_metadata_),
        ~0u,  // no _extensions_
        PROTOBUF_FIELD_OFFSET(::state_message::MapState, _impl_._oneof_case_[0]),
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        ::_pbi::kInvalidFieldOffsetTag,
        ::_pbi::kInvalidFieldOffsetTag,
        PROTOBUF_FIELD_OFFSET(::state_message::MapState, _impl_.parcel_),
        PROTOBUF_FIELD_OFFSET(::state_message::MapMessage, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::state_message::MapMessage, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::state_message::MapMessage, _impl_.timestamp_),
        PROTOBUF_FIELD_OFFSET(::state_message::MapMessage, _impl_.map_states_),
        0,
        ~0u,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::state_message::Position)},
        {10, 20, -1, sizeof(::state_message::AgentState)},
        {22, 32, -1, sizeof(::state_message::AgentMessage)},
        {34, 44, -1, sizeof(::state_message::CellState)},
        {46, -1, -1, sizeof(::state_message::AgentUpdate)},
        {56, -1, -1, sizeof(::state_message::MapState)},
        {67, 77, -1, sizeof(::state_message::MapMessage)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::state_message::_Position_default_instance_._instance,
    &::state_message::_AgentState_default_instance_._instance,
    &::state_message::_AgentMessage_default_instance_._instance,
    &::state_message::_CellState_default_instance_._instance,
    &::state_message::_AgentUpdate_default_instance_._instance,
    &::state_message::_MapState_default_instance_._instance,
    &::state_message::_MapMessage_default_instance_._instance,
};
const char descriptor_table_protodef_state_5fmessage_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\023state_message.proto\022\rstate_message\032\037go"
    "ogle/protobuf/timestamp.proto\"$\n\010Positio"
    "n\022\013\n\003row\030\001 \001(\005\022\013\n\003col\030\002 \001(\005\"I\n\nAgentStat"
    "e\022\020\n\010agent_id\030\001 \001(\t\022)\n\010position\030\002 \001(\0132\027."
    "state_message.Position\"h\n\014AgentMessage\022-"
    "\n\ttimestamp\030\001 \001(\0132\032.google.protobuf.Time"
    "stamp\022)\n\006agents\030\002 \003(\0132\031.state_message.Ag"
    "entState\"E\n\tCellState\022)\n\010position\030\001 \001(\0132"
    "\027.state_message.Position\022\r\n\005value\030\002 \001(\t\""
    "-\n\013AgentUpdate\022\020\n\010agent_id\030\001 \001(\t\022\014\n\004type"
    "\030\002 \001(\t\"x\n\010MapState\022.\n\ncell_state\030\001 \001(\0132\030"
    ".state_message.CellStateH\000\0222\n\014agent_upda"
    "te\030\002 \001(\0132\032.state_message.AgentUpdateH\000B\010"
    "\n\006parcel\"h\n\nMapMessage\022-\n\ttimestamp\030\001 \001("
    "\0132\032.google.protobuf.Timestamp\022+\n\nmap_sta"
    "tes\030\002 \003(\0132\027.state_message.MapState2]\n\021Sh"
    "areStateService\022H\n\nShareState\022\033.state_me"
    "ssage.AgentMessage\032\031.state_message.MapMe"
    "ssage(\0010\001b\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_state_5fmessage_2eproto_deps[1] =
    {
        &::descriptor_table_google_2fprotobuf_2ftimestamp_2eproto,
};
static ::absl::once_flag descriptor_table_state_5fmessage_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_state_5fmessage_2eproto = {
    false,
    false,
    737,
    descriptor_table_protodef_state_5fmessage_2eproto,
    "state_message.proto",
    &descriptor_table_state_5fmessage_2eproto_once,
    descriptor_table_state_5fmessage_2eproto_deps,
    1,
    7,
    schemas,
    file_default_instances,
    TableStruct_state_5fmessage_2eproto::offsets,
    file_level_enum_descriptors_state_5fmessage_2eproto,
    file_level_service_descriptors_state_5fmessage_2eproto,
};
namespace state_message {
// ===================================================================

class Position::_Internal {
 public:
};

Position::Position(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:state_message.Position)
}
Position::Position(
    ::google::protobuf::Arena* arena, const Position& from)
    : Position(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE Position::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void Position::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, row_),
           0,
           offsetof(Impl_, col_) -
               offsetof(Impl_, row_) +
               sizeof(Impl_::col_));
}
Position::~Position() {
  // @@protoc_insertion_point(destructor:state_message.Position)
  SharedDtor(*this);
}
inline void Position::SharedDtor(MessageLite& self) {
  Position& this_ = static_cast<Position&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* Position::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) Position(arena);
}
constexpr auto Position::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(Position),
                                            alignof(Position));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull Position::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_Position_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &Position::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<Position>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &Position::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<Position>(), &Position::ByteSizeLong,
            &Position::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(Position, _impl_._cached_size_),
        false,
    },
    &Position::kDescriptorMethods,
    &descriptor_table_state_5fmessage_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* Position::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2> Position::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::state_message::Position>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 col = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Position, _impl_.col_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(Position, _impl_.col_)}},
    // int32 row = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Position, _impl_.row_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(Position, _impl_.row_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 row = 1;
    {PROTOBUF_FIELD_OFFSET(Position, _impl_.row_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int32 col = 2;
    {PROTOBUF_FIELD_OFFSET(Position, _impl_.col_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void Position::Clear() {
// @@protoc_insertion_point(message_clear_start:state_message.Position)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.row_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.col_) -
      reinterpret_cast<char*>(&_impl_.row_)) + sizeof(_impl_.col_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* Position::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const Position& this_ = static_cast<const Position&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* Position::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const Position& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:state_message.Position)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int32 row = 1;
          if (this_._internal_row() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_row(), target);
          }

          // int32 col = 2;
          if (this_._internal_col() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<2>(
                    stream, this_._internal_col(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:state_message.Position)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t Position::ByteSizeLong(const MessageLite& base) {
          const Position& this_ = static_cast<const Position&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t Position::ByteSizeLong() const {
          const Position& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:state_message.Position)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // int32 row = 1;
            if (this_._internal_row() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_row());
            }
            // int32 col = 2;
            if (this_._internal_col() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_col());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void Position::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Position*>(&to_msg);
  auto& from = static_cast<const Position&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:state_message.Position)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_row() != 0) {
    _this->_impl_.row_ = from._impl_.row_;
  }
  if (from._internal_col() != 0) {
    _this->_impl_.col_ = from._impl_.col_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Position::CopyFrom(const Position& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:state_message.Position)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Position::InternalSwap(Position* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Position, _impl_.col_)
      + sizeof(Position::_impl_.col_)
      - PROTOBUF_FIELD_OFFSET(Position, _impl_.row_)>(
          reinterpret_cast<char*>(&_impl_.row_),
          reinterpret_cast<char*>(&other->_impl_.row_));
}

::google::protobuf::Metadata Position::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class AgentState::_Internal {
 public:
  using HasBits =
      decltype(std::declval<AgentState>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(AgentState, _impl_._has_bits_);
};

AgentState::AgentState(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:state_message.AgentState)
}
inline PROTOBUF_NDEBUG_INLINE AgentState::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::state_message::AgentState& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        agent_id_(arena, from.agent_id_) {}

AgentState::AgentState(
    ::google::protobuf::Arena* arena,
    const AgentState& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  AgentState* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.position_ = (cached_has_bits & 0x00000001u) ? ::google::protobuf::Message::CopyConstruct<::state_message::Position>(
                              arena, *from._impl_.position_)
                        : nullptr;

  // @@protoc_insertion_point(copy_constructor:state_message.AgentState)
}
inline PROTOBUF_NDEBUG_INLINE AgentState::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        agent_id_(arena) {}

inline void AgentState::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.position_ = {};
}
AgentState::~AgentState() {
  // @@protoc_insertion_point(destructor:state_message.AgentState)
  SharedDtor(*this);
}
inline void AgentState::SharedDtor(MessageLite& self) {
  AgentState& this_ = static_cast<AgentState&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.agent_id_.Destroy();
  delete this_._impl_.position_;
  this_._impl_.~Impl_();
}

inline void* AgentState::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) AgentState(arena);
}
constexpr auto AgentState::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(AgentState),
                                            alignof(AgentState));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull AgentState::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_AgentState_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &AgentState::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<AgentState>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &AgentState::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<AgentState>(), &AgentState::ByteSizeLong,
            &AgentState::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(AgentState, _impl_._cached_size_),
        false,
    },
    &AgentState::kDescriptorMethods,
    &descriptor_table_state_5fmessage_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* AgentState::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 1, 41, 2> AgentState::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(AgentState, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::state_message::AgentState>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .state_message.Position position = 2;
    {::_pbi::TcParser::FastMtS1,
     {18, 0, 0, PROTOBUF_FIELD_OFFSET(AgentState, _impl_.position_)}},
    // string agent_id = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(AgentState, _impl_.agent_id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string agent_id = 1;
    {PROTOBUF_FIELD_OFFSET(AgentState, _impl_.agent_id_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // .state_message.Position position = 2;
    {PROTOBUF_FIELD_OFFSET(AgentState, _impl_.position_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::state_message::Position>()},
  }}, {{
    "\30\10\0\0\0\0\0\0"
    "state_message.AgentState"
    "agent_id"
  }},
};

PROTOBUF_NOINLINE void AgentState::Clear() {
// @@protoc_insertion_point(message_clear_start:state_message.AgentState)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.agent_id_.ClearToEmpty();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.position_ != nullptr);
    _impl_.position_->Clear();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* AgentState::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const AgentState& this_ = static_cast<const AgentState&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* AgentState::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const AgentState& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:state_message.AgentState)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string agent_id = 1;
          if (!this_._internal_agent_id().empty()) {
            const std::string& _s = this_._internal_agent_id();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "state_message.AgentState.agent_id");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          cached_has_bits = this_._impl_._has_bits_[0];
          // .state_message.Position position = 2;
          if (cached_has_bits & 0x00000001u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                2, *this_._impl_.position_, this_._impl_.position_->GetCachedSize(), target,
                stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:state_message.AgentState)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t AgentState::ByteSizeLong(const MessageLite& base) {
          const AgentState& this_ = static_cast<const AgentState&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t AgentState::ByteSizeLong() const {
          const AgentState& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:state_message.AgentState)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string agent_id = 1;
            if (!this_._internal_agent_id().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_agent_id());
            }
          }
           {
            // .state_message.Position position = 2;
            cached_has_bits = this_._impl_._has_bits_[0];
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.position_);
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void AgentState::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<AgentState*>(&to_msg);
  auto& from = static_cast<const AgentState&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:state_message.AgentState)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_agent_id().empty()) {
    _this->_internal_set_agent_id(from._internal_agent_id());
  }
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(from._impl_.position_ != nullptr);
    if (_this->_impl_.position_ == nullptr) {
      _this->_impl_.position_ =
          ::google::protobuf::Message::CopyConstruct<::state_message::Position>(arena, *from._impl_.position_);
    } else {
      _this->_impl_.position_->MergeFrom(*from._impl_.position_);
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void AgentState::CopyFrom(const AgentState& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:state_message.AgentState)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void AgentState::InternalSwap(AgentState* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.agent_id_, &other->_impl_.agent_id_, arena);
  swap(_impl_.position_, other->_impl_.position_);
}

::google::protobuf::Metadata AgentState::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class AgentMessage::_Internal {
 public:
  using HasBits =
      decltype(std::declval<AgentMessage>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(AgentMessage, _impl_._has_bits_);
};

void AgentMessage::clear_timestamp() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.timestamp_ != nullptr) _impl_.timestamp_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
AgentMessage::AgentMessage(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:state_message.AgentMessage)
}
inline PROTOBUF_NDEBUG_INLINE AgentMessage::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::state_message::AgentMessage& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        agents_{visibility, arena, from.agents_} {}

AgentMessage::AgentMessage(
    ::google::protobuf::Arena* arena,
    const AgentMessage& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  AgentMessage* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.timestamp_ = (cached_has_bits & 0x00000001u) ? ::google::protobuf::Message::CopyConstruct<::google::protobuf::Timestamp>(
                              arena, *from._impl_.timestamp_)
                        : nullptr;

  // @@protoc_insertion_point(copy_constructor:state_message.AgentMessage)
}
inline PROTOBUF_NDEBUG_INLINE AgentMessage::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        agents_{visibility, arena} {}

inline void AgentMessage::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.timestamp_ = {};
}
AgentMessage::~AgentMessage() {
  // @@protoc_insertion_point(destructor:state_message.AgentMessage)
  SharedDtor(*this);
}
inline void AgentMessage::SharedDtor(MessageLite& self) {
  AgentMessage& this_ = static_cast<AgentMessage&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  delete this_._impl_.timestamp_;
  this_._impl_.~Impl_();
}

inline void* AgentMessage::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) AgentMessage(arena);
}
constexpr auto AgentMessage::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(AgentMessage, _impl_.agents_) +
          decltype(AgentMessage::_impl_.agents_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(AgentMessage), alignof(AgentMessage), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&AgentMessage::PlacementNew_,
                                 sizeof(AgentMessage),
                                 alignof(AgentMessage));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull AgentMessage::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_AgentMessage_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &AgentMessage::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<AgentMessage>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &AgentMessage::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<AgentMessage>(), &AgentMessage::ByteSizeLong,
            &AgentMessage::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(AgentMessage, _impl_._cached_size_),
        false,
    },
    &AgentMessage::kDescriptorMethods,
    &descriptor_table_state_5fmessage_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* AgentMessage::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 2, 0, 2> AgentMessage::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(AgentMessage, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::state_message::AgentMessage>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated .state_message.AgentState agents = 2;
    {::_pbi::TcParser::FastMtR1,
     {18, 63, 1, PROTOBUF_FIELD_OFFSET(AgentMessage, _impl_.agents_)}},
    // .google.protobuf.Timestamp timestamp = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(AgentMessage, _impl_.timestamp_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .google.protobuf.Timestamp timestamp = 1;
    {PROTOBUF_FIELD_OFFSET(AgentMessage, _impl_.timestamp_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // repeated .state_message.AgentState agents = 2;
    {PROTOBUF_FIELD_OFFSET(AgentMessage, _impl_.agents_), -1, 1,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::google::protobuf::Timestamp>()},
    {::_pbi::TcParser::GetTable<::state_message::AgentState>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void AgentMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:state_message.AgentMessage)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.agents_.Clear();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.timestamp_ != nullptr);
    _impl_.timestamp_->Clear();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* AgentMessage::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const AgentMessage& this_ = static_cast<const AgentMessage&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* AgentMessage::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const AgentMessage& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:state_message.AgentMessage)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          cached_has_bits = this_._impl_._has_bits_[0];
          // .google.protobuf.Timestamp timestamp = 1;
          if (cached_has_bits & 0x00000001u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                1, *this_._impl_.timestamp_, this_._impl_.timestamp_->GetCachedSize(), target,
                stream);
          }

          // repeated .state_message.AgentState agents = 2;
          for (unsigned i = 0, n = static_cast<unsigned>(
                                   this_._internal_agents_size());
               i < n; i++) {
            const auto& repfield = this_._internal_agents().Get(i);
            target =
                ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                    2, repfield, repfield.GetCachedSize(),
                    target, stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:state_message.AgentMessage)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t AgentMessage::ByteSizeLong(const MessageLite& base) {
          const AgentMessage& this_ = static_cast<const AgentMessage&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t AgentMessage::ByteSizeLong() const {
          const AgentMessage& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:state_message.AgentMessage)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated .state_message.AgentState agents = 2;
            {
              total_size += 1UL * this_._internal_agents_size();
              for (const auto& msg : this_._internal_agents()) {
                total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
              }
            }
          }
           {
            // .google.protobuf.Timestamp timestamp = 1;
            cached_has_bits = this_._impl_._has_bits_[0];
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.timestamp_);
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void AgentMessage::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<AgentMessage*>(&to_msg);
  auto& from = static_cast<const AgentMessage&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:state_message.AgentMessage)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_agents()->MergeFrom(
      from._internal_agents());
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(from._impl_.timestamp_ != nullptr);
    if (_this->_impl_.timestamp_ == nullptr) {
      _this->_impl_.timestamp_ =
          ::google::protobuf::Message::CopyConstruct<::google::protobuf::Timestamp>(arena, *from._impl_.timestamp_);
    } else {
      _this->_impl_.timestamp_->MergeFrom(*from._impl_.timestamp_);
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void AgentMessage::CopyFrom(const AgentMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:state_message.AgentMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void AgentMessage::InternalSwap(AgentMessage* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.agents_.InternalSwap(&other->_impl_.agents_);
  swap(_impl_.timestamp_, other->_impl_.timestamp_);
}

::google::protobuf::Metadata AgentMessage::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class CellState::_Internal {
 public:
  using HasBits =
      decltype(std::declval<CellState>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(CellState, _impl_._has_bits_);
};

CellState::CellState(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:state_message.CellState)
}
inline PROTOBUF_NDEBUG_INLINE CellState::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::state_message::CellState& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        value_(arena, from.value_) {}

CellState::CellState(
    ::google::protobuf::Arena* arena,
    const CellState& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  CellState* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.position_ = (cached_has_bits & 0x00000001u) ? ::google::protobuf::Message::CopyConstruct<::state_message::Position>(
                              arena, *from._impl_.position_)
                        : nullptr;

  // @@protoc_insertion_point(copy_constructor:state_message.CellState)
}
inline PROTOBUF_NDEBUG_INLINE CellState::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        value_(arena) {}

inline void CellState::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.position_ = {};
}
CellState::~CellState() {
  // @@protoc_insertion_point(destructor:state_message.CellState)
  SharedDtor(*this);
}
inline void CellState::SharedDtor(MessageLite& self) {
  CellState& this_ = static_cast<CellState&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.value_.Destroy();
  delete this_._impl_.position_;
  this_._impl_.~Impl_();
}

inline void* CellState::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) CellState(arena);
}
constexpr auto CellState::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(CellState),
                                            alignof(CellState));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull CellState::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_CellState_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &CellState::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<CellState>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &CellState::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<CellState>(), &CellState::ByteSizeLong,
            &CellState::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(CellState, _impl_._cached_size_),
        false,
    },
    &CellState::kDescriptorMethods,
    &descriptor_table_state_5fmessage_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* CellState::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 1, 37, 2> CellState::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(CellState, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::state_message::CellState>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string value = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(CellState, _impl_.value_)}},
    // .state_message.Position position = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(CellState, _impl_.position_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .state_message.Position position = 1;
    {PROTOBUF_FIELD_OFFSET(CellState, _impl_.position_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // string value = 2;
    {PROTOBUF_FIELD_OFFSET(CellState, _impl_.value_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }}, {{
    {::_pbi::TcParser::GetTable<::state_message::Position>()},
  }}, {{
    "\27\0\5\0\0\0\0\0"
    "state_message.CellState"
    "value"
  }},
};

PROTOBUF_NOINLINE void CellState::Clear() {
// @@protoc_insertion_point(message_clear_start:state_message.CellState)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.value_.ClearToEmpty();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.position_ != nullptr);
    _impl_.position_->Clear();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* CellState::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const CellState& this_ = static_cast<const CellState&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* CellState::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const CellState& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:state_message.CellState)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          cached_has_bits = this_._impl_._has_bits_[0];
          // .state_message.Position position = 1;
          if (cached_has_bits & 0x00000001u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                1, *this_._impl_.position_, this_._impl_.position_->GetCachedSize(), target,
                stream);
          }

          // string value = 2;
          if (!this_._internal_value().empty()) {
            const std::string& _s = this_._internal_value();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "state_message.CellState.value");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:state_message.CellState)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t CellState::ByteSizeLong(const MessageLite& base) {
          const CellState& this_ = static_cast<const CellState&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t CellState::ByteSizeLong() const {
          const CellState& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:state_message.CellState)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string value = 2;
            if (!this_._internal_value().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_value());
            }
          }
           {
            // .state_message.Position position = 1;
            cached_has_bits = this_._impl_._has_bits_[0];
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.position_);
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void CellState::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<CellState*>(&to_msg);
  auto& from = static_cast<const CellState&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:state_message.CellState)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_value().empty()) {
    _this->_internal_set_value(from._internal_value());
  }
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(from._impl_.position_ != nullptr);
    if (_this->_impl_.position_ == nullptr) {
      _this->_impl_.position_ =
          ::google::protobuf::Message::CopyConstruct<::state_message::Position>(arena, *from._impl_.position_);
    } else {
      _this->_impl_.position_->MergeFrom(*from._impl_.position_);
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void CellState::CopyFrom(const CellState& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:state_message.CellState)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void CellState::InternalSwap(CellState* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.value_, &other->_impl_.value_, arena);
  swap(_impl_.position_, other->_impl_.position_);
}

::google::protobuf::Metadata CellState::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class AgentUpdate::_Internal {
 public:
};

AgentUpdate::AgentUpdate(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:state_message.AgentUpdate)
}
inline PROTOBUF_NDEBUG_INLINE AgentUpdate::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::state_message::AgentUpdate& from_msg)
      : agent_id_(arena, from.agent_id_),
        type_(arena, from.type_),
        _cached_size_{0} {}

AgentUpdate::AgentUpdate(
    ::google::protobuf::Arena* arena,
    const AgentUpdate& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  AgentUpdate* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:state_message.AgentUpdate)
}
inline PROTOBUF_NDEBUG_INLINE AgentUpdate::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : agent_id_(arena),
        type_(arena),
        _cached_size_{0} {}

inline void AgentUpdate::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
AgentUpdate::~AgentUpdate() {
  // @@protoc_insertion_point(destructor:state_message.AgentUpdate)
  SharedDtor(*this);
}
inline void AgentUpdate::SharedDtor(MessageLite& self) {
  AgentUpdate& this_ = static_cast<AgentUpdate&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.agent_id_.Destroy();
  this_._impl_.type_.Destroy();
  this_._impl_.~Impl_();
}

inline void* AgentUpdate::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) AgentUpdate(arena);
}
constexpr auto AgentUpdate::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(AgentUpdate),
                                            alignof(AgentUpdate));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull AgentUpdate::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_AgentUpdate_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &AgentUpdate::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<AgentUpdate>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &AgentUpdate::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<AgentUpdate>(), &AgentUpdate::ByteSizeLong,
            &AgentUpdate::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(AgentUpdate, _impl_._cached_size_),
        false,
    },
    &AgentUpdate::kDescriptorMethods,
    &descriptor_table_state_5fmessage_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* AgentUpdate::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 46, 2> AgentUpdate::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::state_message::AgentUpdate>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string type = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(AgentUpdate, _impl_.type_)}},
    // string agent_id = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(AgentUpdate, _impl_.agent_id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string agent_id = 1;
    {PROTOBUF_FIELD_OFFSET(AgentUpdate, _impl_.agent_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string type = 2;
    {PROTOBUF_FIELD_OFFSET(AgentUpdate, _impl_.type_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\31\10\4\0\0\0\0\0"
    "state_message.AgentUpdate"
    "agent_id"
    "type"
  }},
};

PROTOBUF_NOINLINE void AgentUpdate::Clear() {
// @@protoc_insertion_point(message_clear_start:state_message.AgentUpdate)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.agent_id_.ClearToEmpty();
  _impl_.type_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* AgentUpdate::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const AgentUpdate& this_ = static_cast<const AgentUpdate&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* AgentUpdate::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const AgentUpdate& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:state_message.AgentUpdate)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string agent_id = 1;
          if (!this_._internal_agent_id().empty()) {
            const std::string& _s = this_._internal_agent_id();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "state_message.AgentUpdate.agent_id");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // string type = 2;
          if (!this_._internal_type().empty()) {
            const std::string& _s = this_._internal_type();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "state_message.AgentUpdate.type");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:state_message.AgentUpdate)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t AgentUpdate::ByteSizeLong(const MessageLite& base) {
          const AgentUpdate& this_ = static_cast<const AgentUpdate&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t AgentUpdate::ByteSizeLong() const {
          const AgentUpdate& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:state_message.AgentUpdate)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string agent_id = 1;
            if (!this_._internal_agent_id().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_agent_id());
            }
            // string type = 2;
            if (!this_._internal_type().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_type());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void AgentUpdate::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<AgentUpdate*>(&to_msg);
  auto& from = static_cast<const AgentUpdate&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:state_message.AgentUpdate)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_agent_id().empty()) {
    _this->_internal_set_agent_id(from._internal_agent_id());
  }
  if (!from._internal_type().empty()) {
    _this->_internal_set_type(from._internal_type());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void AgentUpdate::CopyFrom(const AgentUpdate& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:state_message.AgentUpdate)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void AgentUpdate::InternalSwap(AgentUpdate* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.agent_id_, &other->_impl_.agent_id_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.type_, &other->_impl_.type_, arena);
}

::google::protobuf::Metadata AgentUpdate::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class MapState::_Internal {
 public:
  static constexpr ::int32_t kOneofCaseOffset =
      PROTOBUF_FIELD_OFFSET(::state_message::MapState, _impl_._oneof_case_);
};

void MapState::set_allocated_cell_state(::state_message::CellState* cell_state) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_parcel();
  if (cell_state) {
    ::google::protobuf::Arena* submessage_arena = cell_state->GetArena();
    if (message_arena != submessage_arena) {
      cell_state = ::google::protobuf::internal::GetOwnedMessage(message_arena, cell_state, submessage_arena);
    }
    set_has_cell_state();
    _impl_.parcel_.cell_state_ = cell_state;
  }
  // @@protoc_insertion_point(field_set_allocated:state_message.MapState.cell_state)
}
void MapState::set_allocated_agent_update(::state_message::AgentUpdate* agent_update) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_parcel();
  if (agent_update) {
    ::google::protobuf::Arena* submessage_arena = agent_update->GetArena();
    if (message_arena != submessage_arena) {
      agent_update = ::google::protobuf::internal::GetOwnedMessage(message_arena, agent_update, submessage_arena);
    }
    set_has_agent_update();
    _impl_.parcel_.agent_update_ = agent_update;
  }
  // @@protoc_insertion_point(field_set_allocated:state_message.MapState.agent_update)
}
MapState::MapState(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:state_message.MapState)
}
inline PROTOBUF_NDEBUG_INLINE MapState::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::state_message::MapState& from_msg)
      : parcel_{},
        _cached_size_{0},
        _oneof_case_{from._oneof_case_[0]} {}

MapState::MapState(
    ::google::protobuf::Arena* arena,
    const MapState& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  MapState* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  switch (parcel_case()) {
    case PARCEL_NOT_SET:
      break;
      case kCellState:
        _impl_.parcel_.cell_state_ = ::google::protobuf::Message::CopyConstruct<::state_message::CellState>(arena, *from._impl_.parcel_.cell_state_);
        break;
      case kAgentUpdate:
        _impl_.parcel_.agent_update_ = ::google::protobuf::Message::CopyConstruct<::state_message::AgentUpdate>(arena, *from._impl_.parcel_.agent_update_);
        break;
  }

  // @@protoc_insertion_point(copy_constructor:state_message.MapState)
}
inline PROTOBUF_NDEBUG_INLINE MapState::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : parcel_{},
        _cached_size_{0},
        _oneof_case_{} {}

inline void MapState::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
MapState::~MapState() {
  // @@protoc_insertion_point(destructor:state_message.MapState)
  SharedDtor(*this);
}
inline void MapState::SharedDtor(MessageLite& self) {
  MapState& this_ = static_cast<MapState&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  if (this_.has_parcel()) {
    this_.clear_parcel();
  }
  this_._impl_.~Impl_();
}

void MapState::clear_parcel() {
// @@protoc_insertion_point(one_of_clear_start:state_message.MapState)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  switch (parcel_case()) {
    case kCellState: {
      if (GetArena() == nullptr) {
        delete _impl_.parcel_.cell_state_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.parcel_.cell_state_);
      }
      break;
    }
    case kAgentUpdate: {
      if (GetArena() == nullptr) {
        delete _impl_.parcel_.agent_update_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.parcel_.agent_update_);
      }
      break;
    }
    case PARCEL_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = PARCEL_NOT_SET;
}


inline void* MapState::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) MapState(arena);
}
constexpr auto MapState::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(MapState),
                                            alignof(MapState));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull MapState::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_MapState_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &MapState::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<MapState>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &MapState::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<MapState>(), &MapState::ByteSizeLong,
            &MapState::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(MapState, _impl_._cached_size_),
        false,
    },
    &MapState::kDescriptorMethods,
    &descriptor_table_state_5fmessage_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* MapState::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 2, 2, 0, 2> MapState::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::state_message::MapState>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // .state_message.CellState cell_state = 1;
    {PROTOBUF_FIELD_OFFSET(MapState, _impl_.parcel_.cell_state_), _Internal::kOneofCaseOffset + 0, 0,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .state_message.AgentUpdate agent_update = 2;
    {PROTOBUF_FIELD_OFFSET(MapState, _impl_.parcel_.agent_update_), _Internal::kOneofCaseOffset + 0, 1,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::state_message::CellState>()},
    {::_pbi::TcParser::GetTable<::state_message::AgentUpdate>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void MapState::Clear() {
// @@protoc_insertion_point(message_clear_start:state_message.MapState)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  clear_parcel();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* MapState::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const MapState& this_ = static_cast<const MapState&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* MapState::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const MapState& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:state_message.MapState)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          switch (this_.parcel_case()) {
            case kCellState: {
              target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                  1, *this_._impl_.parcel_.cell_state_, this_._impl_.parcel_.cell_state_->GetCachedSize(), target,
                  stream);
              break;
            }
            case kAgentUpdate: {
              target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                  2, *this_._impl_.parcel_.agent_update_, this_._impl_.parcel_.agent_update_->GetCachedSize(), target,
                  stream);
              break;
            }
            default:
              break;
          }
          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:state_message.MapState)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t MapState::ByteSizeLong(const MessageLite& base) {
          const MapState& this_ = static_cast<const MapState&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t MapState::ByteSizeLong() const {
          const MapState& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:state_message.MapState)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          switch (this_.parcel_case()) {
            // .state_message.CellState cell_state = 1;
            case kCellState: {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.parcel_.cell_state_);
              break;
            }
            // .state_message.AgentUpdate agent_update = 2;
            case kAgentUpdate: {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.parcel_.agent_update_);
              break;
            }
            case PARCEL_NOT_SET: {
              break;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void MapState::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<MapState*>(&to_msg);
  auto& from = static_cast<const MapState&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:state_message.MapState)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (const uint32_t oneof_from_case = from._impl_._oneof_case_[0]) {
    const uint32_t oneof_to_case = _this->_impl_._oneof_case_[0];
    const bool oneof_needs_init = oneof_to_case != oneof_from_case;
    if (oneof_needs_init) {
      if (oneof_to_case != 0) {
        _this->clear_parcel();
      }
      _this->_impl_._oneof_case_[0] = oneof_from_case;
    }

    switch (oneof_from_case) {
      case kCellState: {
        if (oneof_needs_init) {
          _this->_impl_.parcel_.cell_state_ =
              ::google::protobuf::Message::CopyConstruct<::state_message::CellState>(arena, *from._impl_.parcel_.cell_state_);
        } else {
          _this->_impl_.parcel_.cell_state_->MergeFrom(from._internal_cell_state());
        }
        break;
      }
      case kAgentUpdate: {
        if (oneof_needs_init) {
          _this->_impl_.parcel_.agent_update_ =
              ::google::protobuf::Message::CopyConstruct<::state_message::AgentUpdate>(arena, *from._impl_.parcel_.agent_update_);
        } else {
          _this->_impl_.parcel_.agent_update_->MergeFrom(from._internal_agent_update());
        }
        break;
      }
      case PARCEL_NOT_SET:
        break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void MapState::CopyFrom(const MapState& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:state_message.MapState)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void MapState::InternalSwap(MapState* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.parcel_, other->_impl_.parcel_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::google::protobuf::Metadata MapState::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class MapMessage::_Internal {
 public:
  using HasBits =
      decltype(std::declval<MapMessage>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(MapMessage, _impl_._has_bits_);
};

void MapMessage::clear_timestamp() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.timestamp_ != nullptr) _impl_.timestamp_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
MapMessage::MapMessage(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:state_message.MapMessage)
}
inline PROTOBUF_NDEBUG_INLINE MapMessage::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::state_message::MapMessage& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        map_states_{visibility, arena, from.map_states_} {}

MapMessage::MapMessage(
    ::google::protobuf::Arena* arena,
    const MapMessage& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  MapMessage* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.timestamp_ = (cached_has_bits & 0x00000001u) ? ::google::protobuf::Message::CopyConstruct<::google::protobuf::Timestamp>(
                              arena, *from._impl_.timestamp_)
                        : nullptr;

  // @@protoc_insertion_point(copy_constructor:state_message.MapMessage)
}
inline PROTOBUF_NDEBUG_INLINE MapMessage::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        map_states_{visibility, arena} {}

inline void MapMessage::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.timestamp_ = {};
}
MapMessage::~MapMessage() {
  // @@protoc_insertion_point(destructor:state_message.MapMessage)
  SharedDtor(*this);
}
inline void MapMessage::SharedDtor(MessageLite& self) {
  MapMessage& this_ = static_cast<MapMessage&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  delete this_._impl_.timestamp_;
  this_._impl_.~Impl_();
}

inline void* MapMessage::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) MapMessage(arena);
}
constexpr auto MapMessage::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(MapMessage, _impl_.map_states_) +
          decltype(MapMessage::_impl_.map_states_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(MapMessage), alignof(MapMessage), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&MapMessage::PlacementNew_,
                                 sizeof(MapMessage),
                                 alignof(MapMessage));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull MapMessage::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_MapMessage_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &MapMessage::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<MapMessage>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &MapMessage::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<MapMessage>(), &MapMessage::ByteSizeLong,
            &MapMessage::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(MapMessage, _impl_._cached_size_),
        false,
    },
    &MapMessage::kDescriptorMethods,
    &descriptor_table_state_5fmessage_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* MapMessage::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 2, 0, 2> MapMessage::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(MapMessage, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::state_message::MapMessage>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated .state_message.MapState map_states = 2;
    {::_pbi::TcParser::FastMtR1,
     {18, 63, 1, PROTOBUF_FIELD_OFFSET(MapMessage, _impl_.map_states_)}},
    // .google.protobuf.Timestamp timestamp = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(MapMessage, _impl_.timestamp_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .google.protobuf.Timestamp timestamp = 1;
    {PROTOBUF_FIELD_OFFSET(MapMessage, _impl_.timestamp_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // repeated .state_message.MapState map_states = 2;
    {PROTOBUF_FIELD_OFFSET(MapMessage, _impl_.map_states_), -1, 1,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::google::protobuf::Timestamp>()},
    {::_pbi::TcParser::GetTable<::state_message::MapState>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void MapMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:state_message.MapMessage)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.map_states_.Clear();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.timestamp_ != nullptr);
    _impl_.timestamp_->Clear();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* MapMessage::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const MapMessage& this_ = static_cast<const MapMessage&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* MapMessage::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const MapMessage& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:state_message.MapMessage)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          cached_has_bits = this_._impl_._has_bits_[0];
          // .google.protobuf.Timestamp timestamp = 1;
          if (cached_has_bits & 0x00000001u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                1, *this_._impl_.timestamp_, this_._impl_.timestamp_->GetCachedSize(), target,
                stream);
          }

          // repeated .state_message.MapState map_states = 2;
          for (unsigned i = 0, n = static_cast<unsigned>(
                                   this_._internal_map_states_size());
               i < n; i++) {
            const auto& repfield = this_._internal_map_states().Get(i);
            target =
                ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                    2, repfield, repfield.GetCachedSize(),
                    target, stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:state_message.MapMessage)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t MapMessage::ByteSizeLong(const MessageLite& base) {
          const MapMessage& this_ = static_cast<const MapMessage&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t MapMessage::ByteSizeLong() const {
          const MapMessage& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:state_message.MapMessage)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated .state_message.MapState map_states = 2;
            {
              total_size += 1UL * this_._internal_map_states_size();
              for (const auto& msg : this_._internal_map_states()) {
                total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
              }
            }
          }
           {
            // .google.protobuf.Timestamp timestamp = 1;
            cached_has_bits = this_._impl_._has_bits_[0];
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.timestamp_);
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void MapMessage::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<MapMessage*>(&to_msg);
  auto& from = static_cast<const MapMessage&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:state_message.MapMessage)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_map_states()->MergeFrom(
      from._internal_map_states());
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(from._impl_.timestamp_ != nullptr);
    if (_this->_impl_.timestamp_ == nullptr) {
      _this->_impl_.timestamp_ =
          ::google::protobuf::Message::CopyConstruct<::google::protobuf::Timestamp>(arena, *from._impl_.timestamp_);
    } else {
      _this->_impl_.timestamp_->MergeFrom(*from._impl_.timestamp_);
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void MapMessage::CopyFrom(const MapMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:state_message.MapMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void MapMessage::InternalSwap(MapMessage* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.map_states_.InternalSwap(&other->_impl_.map_states_);
  swap(_impl_.timestamp_, other->_impl_.timestamp_);
}

::google::protobuf::Metadata MapMessage::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace state_message
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_state_5fmessage_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
