# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: position.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'position.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eposition.proto\x12\x08position\"3\n\x0fPositionRequest\x12\x0e\n\x06\x65nable\x18\x01 \x01(\x08\x12\x10\n\x08\x64uration\x18\x02 \x01(\x05\" \n\x08Position\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\"8\n\x10PositionResponse\x12$\n\x08position\x18\x01 \x01(\x0b\x32\x12.position.Position2\\\n\x0fPositionService\x12I\n\x0eStreamPosition\x12\x19.position.PositionRequest\x1a\x1a.position.PositionResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'position_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_POSITIONREQUEST']._serialized_start=28
  _globals['_POSITIONREQUEST']._serialized_end=79
  _globals['_POSITION']._serialized_start=81
  _globals['_POSITION']._serialized_end=113
  _globals['_POSITIONRESPONSE']._serialized_start=115
  _globals['_POSITIONRESPONSE']._serialized_end=171
  _globals['_POSITIONSERVICE']._serialized_start=173
  _globals['_POSITIONSERVICE']._serialized_end=265
# @@protoc_insertion_point(module_scope)
