# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import state_message_pb2 as state__message__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in state_message_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ShareStateServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ShareState = channel.stream_stream(
                '/state_message.ShareStateService/ShareState',
                request_serializer=state__message__pb2.AgentMessage.SerializeToString,
                response_deserializer=state__message__pb2.MapMessage.FromString,
                _registered_method=True)


class ShareStateServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ShareState(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ShareStateServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ShareState': grpc.stream_stream_rpc_method_handler(
                    servicer.ShareState,
                    request_deserializer=state__message__pb2.AgentMessage.FromString,
                    response_serializer=state__message__pb2.MapMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'state_message.ShareStateService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('state_message.ShareStateService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ShareStateService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ShareState(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/state_message.ShareStateService/ShareState',
            state__message__pb2.AgentMessage.SerializeToString,
            state__message__pb2.MapMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
