# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: state_message.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'state_message.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13state_message.proto\x12\rstate_message\x1a\x1fgoogle/protobuf/timestamp.proto\"$\n\x08Position\x12\x0b\n\x03row\x18\x01 \x01(\x05\x12\x0b\n\x03\x63ol\x18\x02 \x01(\x05\"I\n\nAgentState\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\x12)\n\x08position\x18\x02 \x01(\x0b\x32\x17.state_message.Position\"h\n\x0c\x41gentMessage\x12-\n\ttimestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12)\n\x06\x61gents\x18\x02 \x03(\x0b\x32\x19.state_message.AgentState\"E\n\tCellState\x12)\n\x08position\x18\x01 \x01(\x0b\x32\x17.state_message.Position\x12\r\n\x05value\x18\x02 \x01(\t\"-\n\x0b\x41gentUpdate\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\"x\n\x08MapState\x12.\n\ncell_state\x18\x01 \x01(\x0b\x32\x18.state_message.CellStateH\x00\x12\x32\n\x0c\x61gent_update\x18\x02 \x01(\x0b\x32\x1a.state_message.AgentUpdateH\x00\x42\x08\n\x06parcel\"h\n\nMapMessage\x12-\n\ttimestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12+\n\nmap_states\x18\x02 \x03(\x0b\x32\x17.state_message.MapState2]\n\x11ShareStateService\x12H\n\nShareState\x12\x1b.state_message.AgentMessage\x1a\x19.state_message.MapMessage(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'state_message_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_POSITION']._serialized_start=71
  _globals['_POSITION']._serialized_end=107
  _globals['_AGENTSTATE']._serialized_start=109
  _globals['_AGENTSTATE']._serialized_end=182
  _globals['_AGENTMESSAGE']._serialized_start=184
  _globals['_AGENTMESSAGE']._serialized_end=288
  _globals['_CELLSTATE']._serialized_start=290
  _globals['_CELLSTATE']._serialized_end=359
  _globals['_AGENTUPDATE']._serialized_start=361
  _globals['_AGENTUPDATE']._serialized_end=406
  _globals['_MAPSTATE']._serialized_start=408
  _globals['_MAPSTATE']._serialized_end=528
  _globals['_MAPMESSAGE']._serialized_start=530
  _globals['_MAPMESSAGE']._serialized_end=634
  _globals['_SHARESTATESERVICE']._serialized_start=636
  _globals['_SHARESTATESERVICE']._serialized_end=729
# @@protoc_insertion_point(module_scope)
